### ISSUE TITLE
Add times for specification

### ISSUE THREAD

**Issue by madeindjs** [tstehr/RecipeMD#27]
I plan to move my recipes from my Database to markdown files. But I have information about

- baking time
- cooling time
- cooking time
- rest time

Theses informations are very useful but specifications not allow me to write down. Where can I put them ? Should I put them into tags ?

**Comment by tstehr** [comment]
Hi 👋 , thank you for trying RecipeMD 😊

You can add times into tags, if you'd like to. Also, the description can have multiple paragraphs, so you can add a line for the times there: 

```markdown
# Recipe Title

A short description of the recipe.

Baking Time: 20 mins, Cooling Time: 30 mins, Total Time: 50 mins

*tag1, tag2, tag3*

**4 servings, 1 kg**

---

- *500 g* ingredient 1
- ingredient 2 (this one has no unit, e.g for a spice that is added by taste)
- more ingredients as needed...

---

The instructions, that is how to prepare the ingredients
```

The specification doesn't include a syntax for times, since we couldn't think of a use case where you'd need to extract it with the [`recipmd`](https://recipemd.org/reference_implementation.html) library or cli, and our specification tries to be as minimal as possible. 

If you have such use cases I'd be very open to discuss extensions to the spec 👍

**Comment by tstehr** [comment]
I'll close this for now, please ping me if I should reopen it.

**Comment by madeindjs** [comment]
I @tstehr ,

Sorry for my late. I tried to find a way to move my old website with cooking recipes into a static website but I give up for now.

Also I tried [Org](https://orgmode.org/) file format which can be more structured than markdown. Here an example

~~~org
* Starters    :starters:

** Nachos  :Mexican:
  :PROPERTIES:
  :baking: 20 minutes
  :servings: 4 pers
  :END:

  Ingredients

  - nachos
  - cheese

  Step
  ..
~~~ 

But thanks you for your previous answer :smile:
