### ISSUE TITLE
Fenced code blocks at the end of instructions are cut off

### ISSUE THREAD

**Issue by jendrikw** [tstehr/RecipeMD#37]
When a [fenced code block](https://spec.commonmark.org/0.30/#fenced-code-blocks) is the last thing in the instructions, the closing ` ``` ` inside the `recipe.instructions` property is sometimes cut off. When there are fewer than 3 characters in the the last line of the code block, only this many backticks are returned in the string. The bug doesn't happen with more content after the code block.

I think the problem is near https://github.com/tstehr/RecipeMD/blob/3146efb2f0dab95030645419343edeaec873073e/recipemd/data.py#L410-L415

# Test1.md (working)
````
# Bug
---
- *1* Thing
---
Make something.
```
abc
d
```
Have fun!
````

# Output of `recipemd Test1.md`

````
# Bug

---

- *1* Thing

---

Make something.
```
abc
d
```
Have fun!
````

# Test2.md (bug)

````
# Bug
---
- *1* Thing
---
Make something.
```
abc
d
```
````

# Output of `recipemd Test2.md`
````
# Bug

---

- *1* Thing

---

Make something.
```
abc
d
`
````
There is only one backtick in the output.

# Test3.md (bug)
````
# Bug
---
- *1* Thing
---
Make something.
```
abc
de
```
````

# Output of `recipemd Test3.md`
````
# Bug

---

- *1* Thing

---

Make something.
```
abc
de
``
````
There are only two backticks in the output.

# Test4.md (working)
````
# Bug
---
- *1* Thing
---
Make something.
```
abc
def
```
````

# Output of `recipemd Test4.md`
````
# Bug

---

- *1* Thing

---

Make something.
```
abc
def
```
````

**Comment by tstehr** [comment]
Thank you for reporting 👍 

This seems to happen because of a bug in [commonmark.py](https://github.com/readthedocs/commonmark.py), which we use to parse markdown: https://github.com/readthedocs/commonmark.py/issues/310

I'll attempt to work around this for now by ignoring the line offsets.

In the long term we should probably investigate switching to a different markdown implementation such as [markdown-it-py](https://github.com/executablebooks/markdown-it-py), also given previous problems with the library (5d1366a3bc0dbab527f344443be82805105f0aee) and the fact that is might not be maintained any more (see https://github.com/readthedocs/commonmark.py/issues/308).
